#!/bin/sh
### BEGIN INIT INFO
# Provides:          nutcracker
# Required-Start:    $network $remote_fs $local_fs $redis_sentinel
# Required-Stop:     $network $remote_fs $local_fs $redis_sentinel
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Stop/start nutcracker
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC=nutcracker
NAME=nutcracker
USER=nobody
GROUP=nogroup
CONFFILE=/etc/twemproxy.cfg
LOGFILE=/var/run/nutcracker/nutcracker.log
DAEMON=/usr/local/sbin/nutcracker
PIDFILE=/var/run/nutcracker/$NAME.pid
STATSPORT=22222
DAEMON_ARGS="-c $CONFFILE -o $LOGFILE -p $PIDFILE -s $STATSPORT -v 11 -m 512 -d"
#DAEMON_ARGS="-c $CONFFILE -p $PIDFILE -s $STATSPORT -d"
SCRIPTNAME=/etc/init.d/$NAME
FILE_TO_WATCH=/var/lib/redis/nutcracker_update
WATCH_PID_FILE=/var/run/nutcracker/$NAME.WATCH.pid
REDIS_USER=redis

ulimit -Hn 100000
ulimit -Sn 100000

[ -x $DAEMON ] || exit 0

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

. /lib/init/vars.sh

. /lib/lsb/init-functions

do_start()
{
  if [ -f $WATCH_PID_FILE ]; then
    kill $(cat $WATCH_PID_FILE) 2> /dev/null
    rm $WATCH_PID_FILE 2> /dev/null
  fi
  touch $PIDFILE
  mkdir -p /var/run/nutcracker
  chown $USER:$GROUP -R /var/run/nutcracker
  chown $USER:$GROUP $CONFFILE
  chmod 755 /var/run/nutcracker

  echo -n "Starting ${NAME}: "
  start-stop-daemon --start --quiet -m --pidfile $PIDFILE --chuid $USER:$GROUP --exec $DAEMON -- \
    $DAEMON_ARGS
    case "$?" in
      0|1) echo "STARTED." ;;
      2) echo "FAILED." ;;
    esac
  test -e $FILE_TO_WATCH || (touch $FILE_TO_WATCH;chown $REDIS_USER:$REDIS_USER $FILE_TO_WATCH)
  iwatch -c "cat $FILE_TO_WATCH > $CONFFILE; chown $USER:$GROUP $CONFFILE;service $NAME restart" $FILE_TO_WATCH &
  echo $! > $WATCH_PID_FILE
}

do_stop()
{
  if [ -f $WATCH_PID_FILE ]; then
    kill $(cat $WATCH_PID_FILE) 2> /dev/null
    rm $WATCH_PID_FILE 2> /dev/null
  fi
  echo -n "Stopping ${NAME}: "
  start-stop-daemon --stop --quiet --pidfile $PIDFILE --exec $DAEMON || true

  case "$?" in
    0|1) echo "STOPPED.";;
    2) echo "FAILED." ;;
  esac
}

case "$1" in
  start)
    do_start
  ;;
  stop)
    do_stop
  ;;
  status)
    status_of_proc -p $PIDFILE "$DAEMON" nutcracker && exit 0 || exit $?
  ;;
  restart)
    do_stop
    do_start
  ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|status|restart}" >&2
    exit 3
    ;;
esac

exit
$RETVAL
