#! /bin/sh
### BEGIN INIT INFO
# Provides:		redis_s2_3
# Required-Start:	$syslog $remote_fs
# Required-Stop:	$syslog $remote_fs $redis_sentinel
# Should-Start:		$local_fs
# Should-Stop:		$local_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	redis-server (redis_s2_3) - Persistent key-value db
# Description:		redis-server (redis_s2_3) - Persistent key-value db
### END INIT INFO


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/redis-server
CONFIG=/etc/redis/redis_s2_3.conf
DAEMON_ARGS=$CONFIG
NAME=redis_s2_3
DESC=redis_s2_3

RUNDIR=/var/run/redis
PIDFILE=$RUNDIR/redis_s2_3.pid
LOGFILE=/var/log/redis/redis_s2_3.log
RDB=/var/lib/redis/dump_s2_3.rdb
AOF=/var/lib/redis/appendonly_s2_3.aof

test -x $DAEMON || exit 0

if [ -r /etc/default/$NAME ]
then
	. /etc/default/$NAME
fi

. /lib/lsb/init-functions

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	mkdir -p $RUNDIR
	touch $PIDFILE
	chown redis:redis $RUNDIR $PIDFILE $CONFIG
        [ -f $LOGFILE ] && chown redis:redis $LOGFILE
        [ -f $RDB ] && chown redis:redis $RDB
        [ -f $AOF ] && chown redis:redis $AOF
	chmod 755 $RUNDIR

	if [ -n "$ULIMIT" ]
	then
		ulimit -n $ULIMIT
	fi

	if start-stop-daemon --start --quiet --umask 007 --pidfile $PIDFILE --chuid redis:redis --exec $DAEMON -- $DAEMON_ARGS
	then
		echo "$NAME."
	else
		echo "failed"
	fi
	;;
  stop)
	echo -n "Stopping $DESC: "
	if start-stop-daemon --stop --retry forever/TERM/1 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
	then
		echo "$NAME."
	else
		echo "failed"
	fi
	rm -f $PIDFILE
	sleep 1
	;;

  restart|force-reload)
	${0} stop
	${0} start
	;;

  status)
	status_of_proc -p ${PIDFILE} ${DAEMON} ${NAME}
	;;

  *)
	echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
